name: docs links on microstack.run

on: pull_request

jobs:
  check-links:
    if: github.repository == 'canonical-web-and-design/microstack.run'
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install linkchecker
        run: sudo apt update && sudo apt install linkchecker

      - name: Run linkchecker
        run: linkchecker --threads 2 --check-extern --no-warnings https://microstack.run/docs

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=test-bot-channel
